# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7acdaf25a79d200d62d3089301a0f4529597102dad5760043b07fe0ade8147a05d672dd22cd8537c002b36bddda91f2aac85b0a29f8e10792a567be675335b4

test:
  secret_key_base: f9fc7b066cb42825169dc88077731552824697d2b0cee657922903a95f53fdfd6bf306059a4c8e30b785723d500441111fd2253d3a0a3a2b2d8fcf23080ec30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
